# Generated by Django 5.1.7 on 2025-03-27 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GROUP_INVITATION', 'Group Invitation'), ('FUND_CONTRIBUTION', 'Fund Contribution'), ('FUND_WITHDRAWAL', 'Fund Withdrawal'), ('CONTRIBUTION_DISBURSEMENT', 'Contribution Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
