# Generated by Django 5.1.7 on 2025-03-25 16:57

import contribution.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='amount',
        ),
        migrations.AddField(
            model_name='contribution',
            name='payout_status',
            field=models.CharField(choices=[('received', 'Received'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[contribution.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='contributionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[contribution.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='contributionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[contribution.models.is_positive]),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
