# Generated by Django 5.1.7 on 2025-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_contribution_position_alter_contribution_payout_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('upcoming', 'Upcoming')], default='pending', max_length=20),
        ),
    ]
