# Generated by Django 5.1.7 on 2025-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0004_alter_contributionpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='start_date',
            field=models.DateField(),
        ),
    ]
